--DROP TABLE IF EXISTS customers CASCADE;
--DROP TABLE IF EXISTS contacts CASCADE;

CREATE TABLE IF NOT EXISTS customers (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);



CREATE TABLE IF NOT EXISTS contacts(
   id       BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   type      VARCHAR(255)       NOT NULL,
   contact_value       VARCHAR(255)       NOT NULL,
   customer_id BIGINT,
   FOREIGN KEY (customer_id) REFERENCES customers(id)
);


